# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings

title:            re:Profit Lab
email:            rkcudjoe@hookops.com
description:      Let's make your small SaaS app eat competitors' lunch.
baseurl:          '' # The subpath of your site, e.g. /blog
url:              "http://blog.excelwithcode.com" # The base hostname & protocol for your site
github_username:  hookops
twitter_username: hookops

markdown:  kramdown
permalink: pretty
paginate:  9

gems:
  - jekyll-paginate
  - jekyll/tagging

include:
  - _pages

exclude:
  - vendor
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed

# Tags
tag_page_dir:         tag
tag_page_layout:      tag_page
tag_permalink_style:  pretty

# Pages path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

# Authors
authors:
  rkcudjoe:
    name:             Product Developers @ HookOps
    bio:              We make small SaaS apps eat competitors' lunch, with less code. And give you the blueprints, so that you can model and dublicate our results for your digital products.
    gravatar:         https://en.gravatar.com/userimage/51414702/ebe3b1cdeca3eccf75c1d8725980a53d.jpeg
    email:            rkcudjoe+consulting@hookops.com
    website:          http://consulting.hookops.com
    github_username:  hookops
    twitter_username: hookops